# Generated by Django 5.2.10 on 2026-03-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['orden', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='permisosperfil',
            options={'ordering': ['perfil', 'modulo__orden']},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_recuperacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_recuperacion_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_verificacion',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_verificacion_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
